version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/matrix-recorder .

  chartLint:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          description: helm lint
          command: |
            helm lint ./charts/matrix-recorder
      - run:
          description: helm template
          command: |
            helm template ./charts/matrix-recorder


  publishImage:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/matrix-recorder

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-chart.sh web3f/matrix-recorder

  deploy:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          environment:
            GCP_REGION: europe-west3
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - buildImage:
          filters:
            tags:
              only: /.*/
      - chartLint:
          filters:
            tags:
              only: /.*/
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishImage
            - publishChart
