version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/matrix-recorder .

  chartLint:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          description: helm lint
          command: |
            helm lint ./charts/matrix-recorder
      - run:
          description: helm template
          command: |
            helm template ./charts/matrix-recorder

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: setup credentials
          command: |
            echo $BASE_URL > /matrix-recorder/w3f_matrix_log/localstorage/baseUrl
          command: |
            echo $W3F_BACKUPBOT_ACCESS_TOKEN > /matrix-recorder/w3f_matrix_log/localstorage/accessToken
          command: |
            echo $W3F_BACKUPBOT_DEVICE_ID > /matrix-recorder/w3f_matrix_log/localstorage/deviceId
          command: |
            echo $W3F_BACKUPBOT_USER_ID > /matrix-recorder/w3f_matrix_log/localstorage/userId
          environment:
            $BASE_URL: $BASE_URL
            $ACCESS_TOKEN: $W3F_BACKUPBOT_ACCESS_TOKEN
            $DEVICE_ID: $W3F_BACKUPBOT_DEVICE_ID
            $USER_ID: $W3F_BACKUPBOT_USER_ID
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/matrix-recorder

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh web3f/matrix-recorder

  deploy:
    docker:
      - image: web3f/ci-commons:v2.0.1
    steps:
      - checkout
      - run:
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - chartLint:
          filters:
            tags:
              only: /.*/
      - buildImage:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage
            - chartLint
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishImage
            - publishChart
