environment: production

replicaCount: 1
domain: web3.foundation
matrixbot:
  username:
  password:
statefulset:
  updateStrategy: RollingUpdate
serviceAccount:
  create: true
  name: matrix-recorder

image:
  repo: web3f/matrix-recorder
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

certificate:
  enabled: true
