# Default values for bastion.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: deployment
replicaCount: 1

baseUrl:
accessToken:
deviceId:
userId:
domain:
serviceAccount:
  create: true
  name: matrix-recorder

image:
  name: web3f/matrix-recorder
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 7777
resources:
  limits:
     cpu: 200m
     memory: 128Mi
  requests:
     cpu: 100m
     memory: 128Mi
