# Default values for bastion.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: default

baseUrl:
accessToken:
deviceId:
userId:

image:
  name: web3f/matrix-recorder
  pullPolicy: IfNotPresent
service:
  port:
resources:
  limits:
     cpu: 200m
     memory: 128Mi
  requests:
     cpu: 100m
     memory: 128Mi
