environment: production

replicaCount: 1

baseUrl:
accessToken:
deviceId:
userId:

domain: "testnet"

serviceAccount:
  create: true
  name: matrix-recorder

image:
  repo: web3f/matrix-recorder
  tag: v0.0.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7777
