environment: production

replicaCount: 1

baseUrl:
accessToken:
deviceId:
userId:

serviceAccount:
  create: true
  name: matrix-recorder

image:
  repo: web3f/matrix-recorder
  tag: v0.0.10
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
