environment: production

replicaCount: 1

matrixbot:
  username:
  password:

serviceAccount:
  create: true
  name: matrix-recorder

image:
  repo: web3f/matrix-recorder
  tag: v0.0.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
