{{ if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "matrix-recorder.fullname" . }}
  namespace: default
spec:
  secretName: {{ include "matrix-recorder-tls" . }}
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ .Values.domain }}
{{ end }}
