apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix-recorder.fullname" . }}
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace | default  "default"}}
  {{- end }}
  labels:
    {{- include "matrix-recorder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "matrix-recorder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "matrix-recorder.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "matrix-recorder.serviceAccountName" . }}
      containers:
        - name: matrix-recorder
          image: {{ .Values.image.name }}:{{ .Chart.Version }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
               cpu: {{ .Values.resources.limits.cpu }}
               memory: {{ .Values.resources.limits.memory }}
            requests:
               cpu: {{ .Values.resources.requests.cpu }}
               memory: {{ .Values.resources.requests.memory }}

      volumes:
        - name: credentials-volume
          secret:
            secretName: {{ include "matrix-recorder.fullname" . }}-credentials
