apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: recorder-to-html-cronjob
            image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/bin/bash"]
            args: ["-c", "/matrix-recorder/scripts/generatehtml.sh"]
            volumeMounts:
            - name: w3f-matrix-logs-volume
              mountPath: /matrix-recorder/w3f_matrix_log
          restartPolicy: OnFailure
          volumes:
            - name: w3f-matrix-logs-volume
{{ if ne .Values.environment "ci"}}
              persistentVolumeClaim:
                claimName: w3f-matrix-logs-volume-claim
{{ else }}
              emptyDir: {}
{{ end }}
