apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-recorder.fullname" . }}-credentials
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    name: {{ include "matrix-recorder.fullname" . }}-credentials
  annotations:
    description: matrix-recorder credentials
data:
  baseUrl: {{ .Values.baseUrl | default  "baseUrl" | b64enc }}
  accessToken: {{ .Values.accessToken | default  "accessToken" | b64enc }}
  deviceId: {{ .Values.deviceId | default  "deviceId" | b64enc }}
  userId: {{ .Values.userId | default  "userId" | b64enc }}
