apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-recorder.fullname" . }}-credentials
  annotations:
    description: matrixbot credentials
data:
  matrixbot-username: {{ .Values.matrixbot.username | default  "pantelis" | b64enc }}
  matrixbot-password: {{ .Values.matrixbot.password | default  "qewkGVANwU" | b64enc }}
