apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-recorder.fullname" . }}
  labels:
    {{- include "matrix-recorder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default  "LoadBalancer" }}
  ports:
    - name: matrix-recorder
      port: {{ .Values.service.port | default  "8080" }}
      protocol: TCP
  selector:
    {{- include "matrix-recorder.selectorLabels" . | nindent 4 }}
