{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrix-recorder.serviceAccountName" . }}
  labels:
{{ include "matrix-recorder.labels" . | nindent 4 }}
{{- end -}}
