apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-recorder.fullname" . }}
  labels:
    {{- include "matrix-recorder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default  "ClusterIP" }}
  selector:
    {{- include "matrix-recorder.selectorLabels" . | nindent 4 }}
